# Generated by Django 3.0.3 on 2020-03-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Platters',
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
    ]
