# Generated by Django 3.0.3 on 2020-03-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pasta_platters_regularpizza_salad_sicilianpizza_subs_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='small_price',
            field=models.FloatField(blank=True),
        ),
    ]
