# Generated by Django 3.0.3 on 2020-03-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_extras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularPizza',
        ),
    ]
