# Generated by Django 3.0.3 on 2020-03-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_regularpizza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='extra_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pasta',
            old_name='pasta_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='platters',
            old_name='platter_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='regularpizza',
            old_name='pizza_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='salad_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sicilianpizza',
            old_name='pizza_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subs',
            old_name='sub_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='toppings',
            old_name='topping_name',
            new_name='name',
        ),
    ]
