# Generated by Django 3.0.3 on 2020-03-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='items',
            new_name='cart',
        ),
    ]
